# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('vol_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('proffesion', models.CharField(max_length=200)),
                ('identification_no', models.CharField(max_length=120, unique=True)),
                ('county', models.CharField(max_length=255, null=True)),
                ('constituency', models.CharField(max_length=255, null=True)),
                ('ward', models.CharField(max_length=255, null=True)),
                ('what_lured', models.TextField(default='This is a must fill text text')),
                ('any_area', models.TextField(default='This is a must fill text')),
            ],
        ),
    ]
