# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import homes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('home_image', models.ImageField(blank=True, null=True, upload_to=homes.models.upload_location)),
                ('about_home', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('managers_name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('managers_id_no', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
